# MongoDB Standalone Deployment for OpenShift
#
# ℹ️  NOTE: This file is for REFERENCE ONLY.
#     The deploy.sh script creates these resources automatically with a generated password.
#     You don't need to apply this file manually unless doing a custom deployment.
#
# For manual deployment without deploy.sh:
#   1. Create a secret: oc create secret generic mongodb-secret \
#        --from-literal=MONGO_INITDB_ROOT_USERNAME=admin \
#        --from-literal=MONGO_INITDB_ROOT_PASSWORD=<your-secure-password>
#   2. Apply this file: oc apply -f mongodb-standalone.yaml
#
# The deploy.sh script does all of this automatically:
#   ./deploy.sh --host rocketchat.apps.example.com

---
# MongoDB PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
# MongoDB Deployment
# Uses the official MongoDB Community Server UBI image for OpenShift compatibility
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  strategy:
    type: Recreate  # Required for RWO volumes
  template:
    metadata:
      labels:
        app: mongodb
        app.kubernetes.io/name: mongodb
    spec:
      # No securityContext specified - let OpenShift assign appropriate values
      containers:
        - name: mongodb
          image: mongodb/mongodb-community-server:8.2.5-ubi9
          ports:
            - containerPort: 27017
              name: mongodb
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          livenessProbe:
            exec:
              command:
                - mongosh
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - mongosh
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-data

---
# MongoDB Service
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
    app.kubernetes.io/name: mongodb
spec:
  ports:
    - port: 27017
      targetPort: 27017
      name: mongodb
  selector:
    app: mongodb
  type: ClusterIP
